descriptor_extension: yml
package:
  description: 'Anritsu and Spirent NS demo'
  maintainer: 'alberto-m-rocha@alticelabs.com'
  name: 'anrspi'
  vendor: 'anritsu-spirent'
  version: '0.1'
version: '0.5'
