descriptor_extension: yml
files:
- type: application/vnd.5gtango.vnfd
  tags:
  - eu.5gtango
  path: sources/vnfd/vnfd-vepc.yml
- type: application/vnd.5gtango.nsd
  tags:
  - eu.5gtango
  path: sources/nsd/nsd-vepc.yml
package:
  maintainer: AR, ALabs
  name: 5gtango-project-vepc
  vendor: eu.5gtango
  description: 'Athonet vEPC is a 4G mobile core that implements broad mobile network functionality including MME, PGW, SGW, PCRF and HSS'
  version: '0.1'
version: '0.5'
