descriptor_extension: yml
package:
  description: ETSI Plugtest A10NETWORKS Spirent
  maintainer: Felipe Vicens, ATOS, felipe.vicens@atos.net
  name: "etsi-a10networks-spirent"
  vendor: "eu.sonata"
  version: "0.5"
version: '0.5'
